name: QuantumCrate
version: '${project.version}'
main: me.bintanq.quantumcrates.QuantumCrates
api-version: '1.21'
description: Revolutionary crate plugin with Web-First management.
authors: [ bintanq ]

softdepend:
  - PlaceholderAPI
  - DecentHolograms
  - MMOItems
  - ItemsAdder
  - Oraxen

commands:
  quantumcrates:
    description: QuantumCrates main command
    aliases: [ qc, crates, crate ]
    usage: /qc <subcommand>
    permission: quantumcrates.use

permissions:
  quantumcrates.admin:
    description: Full admin access
    default: op
    children:
      quantumcrates.key.give: true
      quantumcrates.massopen: true
      quantumcrates.preview: true
      quantumcrates.use: true
      quantumcrates.web: true
      quantumcrates.bypasscooldown: true
  quantumcrates.use:
    description: Can use crate
    default: true
  quantumcrates.key.give:
    description: Give key to other
    default: op
  quantumcrates.massopen:
    description: Mass open crate
    default: true
  quantumcrates.bypasscooldown:
    description: Bypass crate cooldown
    default: op
  quantumcrates.web:
    description: Generate web dashboard magic link
    default: op
